### PR TITLE
New features + py3 compatiblity 1.1

### PR DESCRIPTION
**Pull request by erwanp**
Hello @aluque , 

I've been QtPlaskin quite extensively in 2016, and started using it again recently. 

I've slightly modified the original version and figured out some of the changes / new features could be merged: 

# Features specific to this Fork: 

Improvements over initial version:

- Dynamic tooltips on plots to analyze graphs with dozens of different lines

- Synchronized timescales over all plots, and dynamic ticks to deal with 
nanosecond to microsecond ranges

- ported to PyQt5 to keep up with the latest Python environnements

- Python3 compatible

- Made qtplaskin an installable Python library

- call qtplaskin from the command line with with `qtplaskin $FOLDER` to analyze a given directory

- faster Results folder loading using Pandas instead of Numpy

---

# Warning: packaging

Changes shouldnt be merged as is. My workflow with QtPlaskin may be slightly different from the original intended one : 

- I'm using QtPlaskin with command line scripts (`qtplaskin $FOLDER`) that read directly from the cloned folder

- I don't use it as a packaged, self-contained app as it was originally intented. I haven't tried any of the packaging tools (`py2exe` etc.) and I don't know how they would perform on the updated version.

- I haven't used in on Mac OS neither (but Windows works fine) 

There is no test routines associated with the original package so some of the features that I don't know of may have been broken (I've never used the Realtime plotting for instance)

However, if this package is to be used in the future I believe the update is worth it, in particular for the [Python 3 compatibility](https://pythonclock.org/)

### CODE REVIEW

**Comment by aluque** [comment]
Dear Erwan,

This looks great!  I’m really glad that qtplaskin was useful enough to you that you worked on improving it.  For a while I have been pointing people to your repo as a more updated version.  I have not used the code for a while and currently I do not have time to actively maintain it so I wonder if I shouldn’t just change the README to point other people to your version and name you as the main maintainer.  What do you think?

Regarding the packaging I found that some people used this software just because it was packaged so conveniently but I had to use some tricks to produce the self-contained distribution files.  I have no idea on whether the packaging libraries have improved since.
 
Best regards,

   Alejandro.

**Comment by erwanp** [comment]
Hi @aluque .  I thought I answered that long ago. Ideally I'd still like to merge into your project so there isnt't more than one version of QtPlaskin around. Also, Python 2 expiring [soon](https://pythonclock.org/) makes at least the Python 3 move important. 

I haven't looked into packaging. Do you have feedbacks from recent users?

We'd need to setup a proper list of features that need to be conserved (like packaging), and test cases. An effort was engaged on my fork where automatic testing is now implemented (see [v1.1.1](https://github.com/erwanp/qtplaskin/pull/4)).

**Comment by aluque** [comment]
Erwan, I really appreciate your taking care of updating and upgrading QtPlaskin.  There are some conflicts with this PR that I have to solve manually and that would require some time. I think a good solution would be for you to join the project as a collaborator, which grants you permission to commit new code.

**Comment by erwanp** [comment]
Thank you Alejandro! I think lately Sergei @githeap has been doing most of the fixes and new implementations, it would be good to have him onboard as a collaborator too (he is already on my fork)

We'll probably start fixing the Packaging issue (https://github.com/erwanp/qtplaskin/issues/11) before proceeding with this Merge Request

**Comment by erwanp** [comment]
Pull Request being processed in #5

**Pull request closed without merging**
